[env:esp32-s3-n32r16]
platform = espressif32
board = esp32-s3-devkitc-1
framework = arduino

board_build.arduino.memory_type = opi_opi
board_build.flash_mode = opi
board_build.psram_type = opi
board_build.flash_size = 32MB
board_build.partitions = partitions_32mb_large_app_ffat.csv

build_src_filter =
  -<*>
  +<main.cpp>
  +<noodle_serial.cpp>

lib_deps =
  symlink:///home/auralius/works/noodle

build_flags =
  -D BOARD_HAS_PSRAM
  -D NOODLE_USE_NONE
  -D NOODLE_POOL_MODE=NOODLE_POOL_MAX
  -D NOODLE_MAX_K=3
  -D NOODLE_FCN_BLOCK=128

upload_protocol = esptool

monitor_speed = 921600
monitor_filters =
  direct

[env:esp32-s3-n16r8]
platform = espressif32
board = esp32-s3-devkitc-1
framework = arduino

board_build.arduino.memory_type = qio_opi
board_build.flash_mode = qio
board_build.psram_type = opi
board_build.flash_size = 16MB
board_build.partitions = partitions_16mb_large_app_ffat.csv

build_src_filter =
  -<*>
  +<main.cpp>
  +<noodle_serial.cpp>

lib_deps =
  symlink:///home/auralius/works/noodle

build_flags =
  -D BOARD_HAS_PSRAM
  -D NOODLE_USE_NONE
  -D NOODLE_POOL_MODE=NOODLE_POOL_MAX
  -D NOODLE_MAX_K=3
  -D NOODLE_FCN_BLOCK=128

upload_protocol = esptool

monitor_speed = 921600
monitor_filters =
  direct

[env:esp32-s3-n16r8-tflm]
platform = espressif32
board = esp32-s3-devkitc-1
framework = arduino

board_build.arduino.memory_type = qio_opi
board_build.flash_mode = qio
board_build.psram_type = opi
board_build.flash_size = 16MB
board_build.partitions = partitions_16mb_large_app_ffat.csv

build_src_filter =
  -<*>
  +<main-tflm.cpp>
  +<noodle_serial.cpp>

lib_deps =
  
build_flags =
  -D BOARD_HAS_PSRAM
  -I /home/auralius/works/libs/Arduino_TensorFlowLite/src

upload_protocol = esptool

monitor_speed = 921600

lib_extra_dirs =
    /home/auralius/works/libs

monitor_filters =
  direct
