site_name: Noodle - The Documentation
site_url: https://auralius.github.io/noodle/
repo_url: https://github.com/auralius/noodle/

theme:
  name: material
  logo: attachments/noodle.png
  favicon: attachments/noodle.png
  features:
    - toc.integrate  # Moves TOC into the left sidebar
markdown_extensions:
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.mark
  - extra

extra_javascript:
  - javascripts/mathjax.js
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js

extra_css:
  - stylesheets/extra.css