;-------------------------------
;--- ESP32-P4 Pico overrides ---
;-------------------------------
[env:esp32p4_pico]
platform = https://github.com/pioarduino/platform-espressif32/releases/download/stable/platform-espressif32.zip
board = esp32-p4
framework = arduino

build_src_filter =
  +<*>
  +<main-p4.cpp>
  -<main-blue-pill.cpp>

monitor_speed = 115200

; --- flash/psram overrides (may be necessary for Waveshare P4 Pico) ---
board_build.flash_size = 32MB
board_upload.flash_size = 32MB
board_build.psram = enabled

; Important: symlink makes VSCode look at your LIVE files, not a copy
lib_deps =
    greiman/SdFat @ ^2.2.3
    symlink:///home/auralius/works/noodle

build_flags =
    -D NOODLE_USE_SD_MMC
    -D NOODLE_POOL_MODE=NOODLE_POOL_MEAN

;---------------------------------
;--- STM32 Blue Pill overrides ---
;---------------------------------
[env:bluepill_f103c8]
platform = ststm32
board = bluepill_f103c8
framework = arduino

build_src_filter =
  -<*>
  -<main-p4.cpp>
  +<main-blue-pill.cpp>
  +<noodle_serial.cpp>
  
lib_deps =
    greiman/SdFat @ ^2.2.3
    symlink:///home/auralius/works/noodle

build_flags =
    -D NOODLE_USE_SDFAT
    -D NOODLE_POOL_MODE=NOODLE_POOL_MEAN
    -D NOODLE_FILE_FORMAT=NOODLE_FILE_FORMAT_BIN
    -D NOODLE_MAX_K=5
    -D NOODLE_FCN_BLOCK=128

upload_protocol = serial
upload_port = /dev/ttyUSB0

monitor_port = /dev/ttyUSB0
monitor_speed = 115200