#ifndef B02_H
#define B02_H

#include <stdint.h>

// Auto-generated by txt2h.py on 2026-02-16T03:54:17
// Source count: 8

const float b02[8] = {
  -0.1665024f, -0.06375653f, -0.2488569f, 0.6488321f, -0.02546179f, 2.888035f, 1.574996f, 1.698881f,
};

#define B02_LEN (8u)

#endif // B02_H