#ifndef B04_H
#define B04_H

#include <stdint.h>

// Auto-generated by txt2h.py on 2026-02-16T03:54:17
// Source count: 16

const float b04[16] = {
  -0.1590768f, 1.294096f, 1.960374f, 0.04447803f, 3.209736f, 0.2652511f, 0.05461693f, 1.854444f,
  1.111688f, -1.40019f, -0.1734115f, 3.493563f, -0.6977845f, -0.8433772f, 1.128297f, 1.527815f,
};

#define B04_LEN (16u)

#endif // B04_H