[env:esp32-s3-n32r16]
platform = espressif32
board = esp32-s3-devkitc-1
framework = arduino

board_build.arduino.memory_type = opi_opi
board_build.flash_mode = opi
board_build.psram_type = opi
board_upload.flash_size = 32MB

build_src_filter =
    -<*>
    +<main.cpp>
    +<noodle_serial.cpp>

build_flags = 
    -DBOARD_HAS_PSRAM
    -DARDUINO_USB_CDC_ON_BOOT=1
    -DNOODLE_USE_NONE
    -DNOODLE_POOL_MODE=NOODLE_POOL_NONE
    -DNOODLE_MAX_K=5

monitor_speed = 921600
monitor_dtr = 0
monitor_rts = 0

lib_deps =
    symlink:///home/auralius/works/noodle
    
    
[env:esp32-s3-n32r16-tflm]
platform = espressif32
board = esp32-s3-devkitc-1
framework = arduino

board_build.arduino.memory_type = opi_opi
board_build.flash_mode = opi
board_build.psram_type = opi
board_upload.flash_size = 32MB

build_src_filter =
    -<*>
    +<main_tflm_denoising_benchmark.cpp>
    +<noodle_serial.cpp>

build_flags =
    -DBOARD_HAS_PSRAM
    -DARDUINO_USB_CDC_ON_BOOT=1
    -DAE_VERBOSE=0
    -I/home/auralius/works/libs/Arduino_TensorFlowLite/src

monitor_speed = 921600
monitor_dtr = 0
monitor_rts = 0

lib_extra_dirs =
    /home/auralius/works/libs

lib_deps =
