[env:rp2350_firenet]
platform = https://github.com/maxgerhardt/platform-raspberrypi.git
board = rpipico2
framework = arduino

build_src_filter =
  -<*>
  +<main_rp2350_firenet.cpp>
  +<noodle_serial.cpp>

lib_deps =
  symlink:///home/auralius/works/noodle

build_flags =
  -D NOODLE_USE_NONE
  -D NOODLE_POOL_MODE=NOODLE_POOL_MAX
  -D NOODLE_MAX_K=3
  -D NOODLE_FCN_BLOCK=128

upload_protocol = picotool

monitor_speed = 921600
monitor_filters =
  direct