#ifndef B01_H
#define B01_H

#include <stdint.h>

// Auto-generated by txt2h.py on 2026-02-16T03:54:17
// Source count: 8

const float b01[8] = {
  0.7962068f, 0.5667514f, 1.504084f, 1.01485f, 1.368334f, 0.7852963f, 0.5565313f, 1.320734f,
};

#define B01_LEN (8u)

#endif // B01_H