#ifndef B03_H
#define B03_H

#include <stdint.h>

// Auto-generated by txt2h.py on 2026-02-16T03:54:17
// Source count: 16

const float b03[16] = {
  -0.7918872f, 0.9686425f, -0.2310693f, 0.4033405f, 0.5587362f, 0.08204004f, -0.9798577f, 1.727355f,
  1.080012f, -0.02183658f, 1.43893f, 0.697417f, -1.602405f, -0.03496703f, 1.799499f, -0.1352036f,
};

#define B03_LEN (16u)

#endif // B03_H