#ifndef B28_H
#define B28_H

#include <stdint.h>

// Auto-generated by txt2h.py on 2026-02-16T03:54:17
// Source count: 2

const float b28[2] = {
  0.1081055f, -0.1081056f,
};

#define B28_LEN (2u)

#endif // B28_H