[env:esp32-s3-n32r16]
platform = espressif32
board = esp32-s3-devkitc-1
framework = arduino

board_build.f_cpu = 240000000L
board_build.f_flash = 80000000L
board_build.arduino.memory_type = opi_opi
board_build.flash_mode = opi
board_build.psram_type = opi
board_build.flash_size = 32MB
board_upload.flash_size = 32MB
board_build.filesystem = fatfs
board_build.partitions = partition-s3.csv

build_src_filter =
    -<*>
    +<main.cpp>
    +<noodle_serial.cpp>

build_flags = 
    -D BOARD_HAS_PSRAM
    -D ARDUINO_USB_CDC_ON_BOOT=1
    -D NOODLE_POOL_MODE=NOODLE_POOL_NONE
    -D NOODLE_MAX_K=5
    -D NOODLE_USE_FFAT

monitor_speed = 921600
monitor_dtr = 0
monitor_rts = 0

lib_deps =
    symlink:///home/auralius/works/noodle

[env:esp32p4_pico]
platform = https://github.com/pioarduino/platform-espressif32/releases/download/stable/platform-espressif32.zip
board = esp32-p4
framework = arduino

board_build.f_cpu = 400000000L
board_build.f_flash = 80000000L

board_build.flash_size = 32MB
board_upload.flash_size = 32MB
board_build.psram = enabled

board_build.filesystem = fatfs
board_build.partitions = partition-p4.csv

build_src_filter =
    -<*>
    +<main.cpp>
    +<noodle_serial.cpp>

build_flags =
    -D BOARD_HAS_PSRAM
    -D NOODLE_POOL_MODE=NOODLE_POOL_MAX
    -D NOODLE_MAX_K=5
    -D NOODLE_USE_FFAT
    -D NOODLE_FILE_FORMAT=NOODLE_FILE_FORMAT_BIN
    -D NOODLE_FCN_BLOCK=256
    -D CORE_DEBUG_LEVEL=0
    -O3

monitor_speed = 921600
monitor_dtr = 0
monitor_rts = 0

lib_deps =
    symlink:///home/auralius/works/noodle