#ifndef W10_H
#define W10_H

#include <stdint.h>

// Auto-generated by txt2h.py on 2026-02-14T11:20:44
// Source count: 8

const float w10[8] = {
  2.156f, 2.488f, 2.413f, 2.416f, 1.966f, 2.233f, 2.729f, 2.016f,
};

#define W10_LEN (8u)

#endif // W10_H