[env:rp2350_firenet]
platform = https://github.com/maxgerhardt/platform-raspberrypi.git
board = rpipico2
framework = arduino

build_src_filter =
  -<*>
  +<main1.cpp>
  +<tinyresnet_model_data.cpp>
  +<noodle_serial.cpp>

lib_deps =
  symlink:///home/auralius/works/noodle

build_flags =
  -D NOODLE_USE_NONE
  -D NOODLE_POOL_MODE=NOODLE_POOL_NONE
  -D NOODLE_MAX_K=3
  -D NOODLE_FCN_BLOCK=128
  -D NOODLE_BUFFER_ARENA_INITIAL_BYTES=241664
  -I /home/auralius/works/libs/Arduino_TensorFlowLite/src

lib_extra_dirs =
    /home/auralius/works/libs

upload_protocol = picotool

monitor_speed = 921600
monitor_filters =
  direct