[env:mega2560]
platform = atmelavr
board = megaatmega2560
framework = arduino
monitor_speed = 115200

lib_deps =
  ;prenticedavid/MCUFRIEND_kbv @ ^3.0.0
  ;adafruit/Adafruit TouchScreen @ ^1.1.4
  ;adafruit/Adafruit GFX Library @ ^1.11.10
  ;adafruit/Adafruit BusIO @ ^1.16.1
  greiman/SdFat @ ^2.2.3
  symlink:///home/auralius/works/noodle

build_flags =
  -Os
  -flto
  -ffunction-sections
  -fdata-sections
  -D PIO_FRAMEWORK_ARDUINO_ENABLE_PROGMEM
  -D NOODLE_USE_SDFAT
  -D NOODLE_POOL_MODE=NOODLE_POOL_MEAN
  -D NOODLE_FILE_FORMAT=1
  -D NOODLE_FCN_BLOCK=64

build_unflags =
  -O2

board_build.extra_flags =
  -Wl,--gc-sections