; --- Settings for ESP32 ---
; --- BloodMNIST dataset ---
[env:esp32-blood]
platform = espressif32
board = esp32dev
framework = arduino
monitor_speed = 921600

build_src_filter =
  +<*>
  +<blood.cpp>
  -<pneumonia.cpp>

; FILESYSTEM & PARTITION
; This creates the space for your .txt weight files
board_build.partitions = no_ffat.csv
;board_build.filesystem = fatfs
;board_build.partitions = partition.csv

; LIBRARIES
; PlatformIO will download these automatically
lib_deps =
    ;https://github.com/auralius/noodle.git
    symlink:///home/auralius/works/noodle  ; Local path to Noodle library

; This avoids having to edit User_Setup.h inside the library
build_flags =
  ; --- Noodle Library Settings
  -D NOODLE_USE_NONE
  -D NOODLE_POOL_MODE=NOODLE_POOL_NONE
  -D NOODLE_MAX_K=3

; --- Settings for ESP32 ---
; --- PnemoniaMNIST dataset ---
[env:esp32-pneumonia]
platform = espressif32
board = esp32dev
framework = arduino
monitor_speed = 921600

build_src_filter =
  +<*>
  -<blood.cpp>
  +<pneumonia.cpp>

; FILESYSTEM & PARTITION
; This creates the space for your .txt weight files
board_build.partitions = no_ffat.csv
;board_build.filesystem = fatfs
;board_build.partitions = partition.csv

; LIBRARIES
; PlatformIO will download these automatically
lib_deps =
    ;https://github.com/auralius/noodle.git
    symlink:///home/auralius/works/noodle  ; Local path to Noodle library

; This avoids having to edit User_Setup.h inside the library
build_flags =
  ; --- Noodle Library Settings
  -D NOODLE_USE_NONE
  -D NOODLE_POOL_MODE=NOODLE_POOL_NONE
  -D NOODLE_MAX_K=3

; --------------------------------------------------------------------------------------------
; --- Settings for RASPI Pico black pcb ---
; --- BloodMNIST dataset ---
[env:rpi_pico-blood]
platform = raspberrypi
board = pico
framework = arduino
monitor_speed = 115200

build_src_filter =
  +<*>
  +<blood.cpp>
  -<pneumonia.cpp>

; If you want faster upload, many setups support this:
; upload_protocol = picotool
lib_deps =
  ;https://github.com/auralius/noodle.git
  symlink:///home/auralius/works/noodle 

build_flags =
  ; --- Noodle Library Settings
  ; (RP2040 has no FFat; use in-memory weights or SD/SPI flash if you add it)
  -D NOODLE_USE_NONE
  -D NOODLE_POOL_MODE=NOODLE_POOL_NONE
  -D NOODLE_MAX_K=3

; --------------------------------------------------------------------------------------------
; --- Settings for RASPI Pico black pcb ---
; --- PneumoniaMNIST dataset ---
[env:rpi_pico-pneumonia]
platform = raspberrypi
board = pico
framework = arduino
monitor_speed = 921600

build_src_filter =
  +<*>
  -<blood.cpp>
  +<pneumonia.cpp>

; If you want faster upload, many setups support this:
; upload_protocol = picotool
lib_deps =
  ;https://github.com/auralius/noodle.git
  symlink:///home/auralius/works/noodle 

build_flags =
  ; --- Noodle Library Settings
  ; (RP2040 has no FFat; use in-memory weights or SD/SPI flash if you add it)
  -D NOODLE_USE_NONE
  -D NOODLE_POOL_MODE=NOODLE_POOL_NONE
  -D NOODLE_MAX_K=3

; --------------------------------------------------------------------------------------------
; --- Settings for STM32U585CIU6 (WeAct Mini Core) ---
; --- PneumoniaMNIST dataset ---
; --------------------------------------------------------------------------------------------
[env:stm32u585-pneumonia]
platform = ststm32
framework = arduino
board = genericSTM32U585CIU6_custom

monitor_speed = 921600
monitor_dtr = 1

build_src_filter =
  +<*>
  -<blood.cpp>
  +<pneumonia.cpp>

lib_deps =
  symlink:///home/auralius/works/noodle

build_flags =
  -O3
  -ffast-math
  -funroll-loops

  -D NOODLE_USE_NONE
  -D NOODLE_POOL_MODE=NOODLE_POOL_NONE
  -D NOODLE_MAX_K=3

  -D PIO_FRAMEWORK_ARDUINO_ENABLE_CDC
  -D USBCON
  -D STM32U585xx

upload_protocol = dfu

; --------------------------------------------------------------------------------------------
; --- Settings for STM32U585CIU6 DEBUG ---
; --- PneumoniaMNIST dataset ---
; --------------------------------------------------------------------------------------------
[env:stm32u585-pneumonia-debug]
platform = ststm32
framework = arduino
board = genericSTM32U585CIU6_custom

monitor_speed = 921600
monitor_dtr = 1

build_src_filter =
  +<*>
  -<blood.cpp>
  +<pneumonia.cpp>

lib_deps =
  symlink:///home/auralius/works/noodle

build_type = debug

build_flags =
  -Og
  -g3

  -D NOODLE_USE_NONE
  -D NOODLE_POOL_MODE=NOODLE_POOL_NONE
  -D NOODLE_MAX_K=3

  -D PIO_FRAMEWORK_ARDUINO_ENABLE_CDC
  -D USBCON
  -D STM32U585xx

upload_protocol = stlink
debug_tool = stlink
debug_init_break = tbreak setup

debug_build_flags =
  -Og
  -g3

debug_extra_cmds =
  monitor reset halt